staticcheck
	❯ go run honnef.co/go/tools/cmd/staticcheck@latest ./...
	gateway.go:83:41: unnecessary use of fmt.Sprintf (S1039)
	gateway.go:91:41: unnecessary use of fmt.Sprintf (S1039)
	gateway.go:98:41: unnecessary use of fmt.Sprintf (S1039)
	gateway.go:105:4: printf-style function with dynamic format string and no further arguments should use print-style function instead (SA1006)
	handler.go:23:5: error var ConfigMismatchError should have name of the form ErrFoo (ST1012)
	handler.go:23:27: error strings should not be capitalized (ST1005)
	handler.go:26:5: error var EncapsulationError should have name of the form ErrFoo (ST1012)
	handler.go:26:26: error strings should not be capitalized (ST1005)
	handler.go:29:5: error var PayloadMarshallingError should have name of the form ErrFoo (ST1012)
	handler.go:29:31: error strings should not be capitalized (ST1005)
	handler.go:32:5: error var GatewayTargetForbiddenError should have name of the form ErrFoo (ST1012)
	handler.go:32:35: error strings should not be capitalized (ST1005)
	handler.go:35:5: error var GatewayInternalServerError should have name of the form ErrFoo (ST1012)
	handler.go:35:34: error strings should not be capitalized (ST1005)
	main.go:67:2: field metricsFactory is unused (U1000)
	proto_codec.go:84:15: error strings should not be capitalized (ST1005)
	proto_codec.go:88:15: error strings should not be capitalized (ST1005)
	exit status 1